name: rf-ci-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn==1.4.2
      - pandas
      - numpy
      - matplotlib
      - seaborn
